### ISSUE TITLE
devcontainer: ERROR resolve image config

### ISSUE THREAD

**Issue by mengzhuo** [moonbitlang/core#1196]
```
Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux
```

<details>
```
[81 ms] Dev Containers 0.388.0 in VS Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6).
[81 ms] Start: Resolving Remote
[102 ms] Setting up container for folder or workspace: d:\Users\mzh\vscode\core
[103 ms] Context: desktop-linux
[104 ms] Start: Run: wsl -l -v
[252 ms] Start: Run: wsl -d Arch -e /bin/sh -c echo ~
[607 ms] Start: Run: wsl -d Arch -e /bin/sh -c cd '/home/mzh' && /bin/sh
[616 ms] Start: Run in host: id -un
[764 ms] mzh
[765 ms] 
[766 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'mzh' || grep -E '^mzh|^[^:]*:[^:]*:mzh:' /etc/passwd || true)
[771 ms] Start: Run in host: echo ~
[772 ms] /home/mzh
[773 ms] 
[773 ms] Start: Run in host: test -f '/home/mzh/.vscode-server/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/server/node'
[775 ms] 
[775 ms] 
[775 ms] Exit code 1
[775 ms] Start: Run in host: test -f '/home/mzh/.vscode/cli/servers/Stable-65edc4939843c90c34d61f4ce11704f09d3e5cb6/server/node'
[777 ms] 
[778 ms] 
[778 ms] Exit code 1
[778 ms] Start: Run in host: test -f '/home/mzh/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/node'
[780 ms] 
[780 ms] 
[780 ms] Exit code 1
[780 ms] Start: Run in host: test -f '/home/mzh/.vscode-remote-containers/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/node'
[782 ms] 
[782 ms] 
[782 ms] Start: Run in host: test -f '/home/mzh/.vscode-remote-containers/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/node_modules/node-pty/package.json'
[783 ms] 
[784 ms] 
[784 ms] Start: Run in host: test -f '/home/mzh/.vscode-remote-containers/dist/vscode-remote-containers-server-0.388.0.js'
[785 ms] 
[786 ms] 
[790 ms] userEnvProbe: loginInteractiveShell (default)
[790 ms] userEnvProbe: not found in cache
[791 ms] userEnvProbe shell: /usr/bin/bash
[896 ms] userEnvProbe PATHs:
Probe:     '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/Docker/host/bin:/mnt/d/Program Files/Go/bin:/mnt/c/Users/mzh/.moon/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/Docker/host/bin:/mnt/c/Users/mzh/AppData/Local/Microsoft/WindowsApps:/mnt/d/Users/mzh/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/mzh/go/bin:/mnt/d/Program Files/JetBrains/CLion 2024.2.3/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
Container: None
[904 ms] Start: Run in Host: wslpath -w /run/user/1000/wayland-0
[910 ms] Start: Check Docker is running
[911 ms] Start: Run: docker version
[1337 ms] Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:17:17 2024
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.34.3 (170107)
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
[1338 ms]   Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[1347 ms] Start: Run: docker volume ls -q
[1723 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=d:\Users\mzh\vscode\core --filter label=vsch.quality=stable
[2057 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\Users\mzh\vscode\core --filter label=devcontainer.config_file=d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json
[2365 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\Users\mzh\vscode\core
[2658 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\Users\mzh\vscode\core
[2992 ms] Running Dev Containers CLI:   up --user-data-folder c:\Users\mzh\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-2691473b-e0fb-4d22-9ca3-c8488296245f1730785536725 --workspace-folder d:\Users\mzh\vscode\core --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=d:\Users\mzh\vscode\core --id-label devcontainer.config_file=d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Arch\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-1c2094ea-bfa0-464f-8284-862de7c9e128.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[3001 ms] ProxyResolver#loadSystemCertificates count
[3004 ms] ProxyResolver#loadSystemCertificates count filtered
[3005 ms] Start: Run: D:\Users\mzh\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\mzh\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-2691473b-e0fb-4d22-9ca3-c8488296245f1730785536725 --workspace-folder d:\Users\mzh\vscode\core --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=d:\Users\mzh\vscode\core --id-label devcontainer.config_file=d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Arch\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-1c2094ea-bfa0-464f-8284-862de7c9e128.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[4324 ms] @devcontainers/cli 0.71.0. Node.js v20.18.0. win32 10.0.22631 x64.
[4324 ms] Start: Run: docker buildx version
[5672 ms] github.com/docker/buildx v0.16.2-desktop.1 081c21b9e461293ae243a1ff813a680a4f5f8fb9
[5672 ms] 
[5672 ms] Start: Run: docker -v
[6008 ms] Start: Resolving Remote
[6012 ms] Start: Run: git rev-parse --show-cdup
[6251 ms] Loading 41 extra certificates from C:\Users\mzh\AppData\Local\Temp\vsch\certificates-0ca966eee7fb5026e32c05048998c681727c65e8d2ac7d5ca41544e5cc87350e.pem.
[6907 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=d:\Users\mzh\vscode\core --filter label=devcontainer.config_file=d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json
[7251 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:noble
[7688 ms] Resolving Feature dependencies for './moonbit-cli'...
[7688 ms] * Processing feature: ./moonbit-cli
[7688 ms] Local disk feature.
[7704 ms] * Fetching feature: moonbit_0_file-path
[7719 ms] Start: Run: docker buildx build --load --build-context dev_containers_feature_content_source=C:\Users\mzh\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1730785547357 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:noble --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f C:\Users\mzh\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1730785547357\Dockerfile.extended -t vsc-core-dece6adc8a0ededd15c3a090d5c8f57284b3e8ff3965a989201bcb909a9233ad-features c:\Users\mzh\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\empty-folder

[+] Building 2.1s (3/3) FINISHED                           docker:desktop-linux
 => [internal] load build definition from Dockerfile.extended              0.0s
 => => transferring dockerfile: 1.87kB                                     0.0s
 => ERROR resolve image config for docker-image://docker.io/docker/docker  1.8s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io           0.0s
------
 > resolve image config for docker-image://docker.io/docker/dockerfile:1.4:
------
Dockerfile.extended:1
--------------------
   1 | >>> # syntax=docker/dockerfile:1.4
   2 |     ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder
   3 |
--------------------
ERROR: failed to solve: failed to resolve source metadata for docker.io/docker/d
ockerfile:1.4: failed to authorize: failed to fetch oauth token: Post "https://a
uth.docker.io/token": read tcp 10.0.0.137:51934->54.227.20.253:443: wsarecv: An
existing connection was forcibly closed by the remote host.

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux
/sqo347vua5e4zc00jg99iwp9y
[11790 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=C:\Users\mzh\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1730785547357 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:noble --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -f C:\Users\mzh\AppData\Local\Temp\devcontainercli\container-features\0.71.0-1730785547357\Dockerfile.extended -t vsc-core-dece6adc8a0ededd15c3a090d5c8f57284b3e8ff3965a989201bcb909a9233ad-features c:\Users\mzh\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\empty-folder
[11790 ms]     at ytA (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:465:1260)
[11790 ms]     at bH (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:465:1002)
[11790 ms]     at async TtA (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:3848)
[11791 ms]     at async iB (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:4963)
[11791 ms]     at async wrA (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:663:203)
[11791 ms]     at async DrA (c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:662:14830)
[11791 ms]     at async c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js:482:1190
[11806 ms] Exit code 1
[11814 ms] Command failed: D:\Users\mzh\AppData\Local\Programs\Microsoft VS Code\Code.exe c:\Users\mzh\.vscode\extensions\ms-vscode-remote.remote-containers-0.388.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\mzh\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-2691473b-e0fb-4d22-9ca3-c8488296245f1730785536725 --workspace-folder d:\Users\mzh\vscode\core --workspace-mount-consistency cached --gpu-availability detect --id-label devcontainer.local_folder=d:\Users\mzh\vscode\core --id-label devcontainer.config_file=d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\Users\mzh\vscode\core\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Arch\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-1c2094ea-bfa0-464f-8284-862de7c9e128.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[11814 ms] Exit code 1

```
</details>

**Comment by Lampese** [comment]
cc @peter-jerry-ye
