### ISSUE TITLE
add `moon test --target js` to CI

### ISSUE THREAD

**Issue by bobzhang** [moonbitlang/core#213]
```

test moonbitlang/core/assertion/assertion.mbt::assert_is.is.not failed: FAILED:/Users/hongbozhang/git/core/assertion/assertion.mbt:154:3-154:39 `Ok(()) != Ok(())`
test moonbitlang/core/assertion/assertion.mbt::assert_is_not.is.not failed: FAILED:/Users/hongbozhang/git/core/assertion/assertion.mbt:197:3-197:43 `Err("FAILED:/Users/hongbozhang/git/core/assertion/assertion.mbt:197:13-197:34 `not(\"x:1\" is \"x:1\")`") == Ok(())`






/Users/hongbozhang/git/core/target/js/release/test/double/double.internal_test.js:705
  const $42$bind = moonbitlang$core$builtin$$inspect({ $42$label0: moonbitlang$core$double$$Double$to_string(0), $42$label1: $$to_string$7$ }, "0.0", "/Users/hongbozhang/git/core/double/ryu.mbt:663:3-663:43", [new Option$Some$8$("/Users/hongbozhang/git/core/double/ryu.mbt:663:11-663:26"), new Option$Some$8$("/Users/hongbozhang/git/core/double/ryu.mbt:663:37-663:42"), Option$None$8$, Option$None$8$]);
                                                                   ^

ReferenceError: moonbitlang$core$double$$Double$to_string is not defined
    at moonbitlang$core$double$$__test_7279752e6d6274_0 (/Users/hongbozhang/git/core/target/js/release/test/double/double.internal_test.js:705:68)
    at /Users/hongbozhang/git/core/target/js/release/test/double/double.internal_test.js:801:22
    at Object.<anonymous> (/Users/hongbozhang/git/core/target/js/release/test/double/double.internal_test.js:830:2)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.10.0
Error when running /Users/hongbozhang/git/core/target/js/release/test/double/double.internal_test.js: Failed to run the test







/Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:18
  throw new Error(a);
  ^

Error: called `Result::unwrap()` on an `Err` value
    at $raise (/Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:18:9)
    at moonbitlang$core$result$$Result$unwrap$0$ (/Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:108:7)
    at moonbitlang$core$math$$__test_616c676562726169632e6d6274_1 (/Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:471:3)
    at /Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:704:22
    at Object.<anonymous> (/Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js:733:2)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)

Node.js v20.10.0
Error when running /Users/hongbozhang/git/core/target/js/release/test/math/math.internal_test.js: Failed to run the test









test moonbitlang/core/strconv/traits.mbt::parse_int64_base failed: FAILED:/Users/hongbozhang/git/core/strconv/int.mbt:364:5-364:59 `Ok(-9223372036854775808) == Ok(9223372036854775808)`




Total tests: 364, passed: 361, failed: 3.
```

**Comment by hackwaly** [comment]
This first problem is assert_is use physic_equal under the hood, which behavior is not cross platform consistent. In javascript target, two string has same contents are treat as physic_equal true. I'll open a pull request to fix it.

The `moonbitlang$core$double$$Double$to_string` problem may be bug introduced at !2992.
